version: '3.8'

services:
  blinkit-watcher:
    image: ayushshivaji/blinkit-watcher:latest
    container_name: blinkit-watcher
    environment:
      - NOTIFICATION_SERVICE_URL=http://localhost:10000/publish
      - PINCODE=201017
    restart: unless-stopped
    network_mode: host